-- V001__create_program_type_table.sql
-- AB#1889 Create program_type table

CREATE TABLE program_type (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name NVARCHAR(100) NOT NULL,
    type_name_fr NVARCHAR(100) NOT NULL
);
