-- V002__create_program_table.sql
-- AB#1890 Create program table

CREATE TABLE program (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_name NVARCHAR(200) NOT NULL,
    program_description NVARCHAR(MAX) NOT NULL,
    program_type_id INT NOT NULL,
    status NVARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    reviewer_comments NVARCHAR(MAX),
    submitted_at DATETIME2,
    reviewed_at DATETIME2,
    created_at DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME2,
    created_by NVARCHAR(100),
    CONSTRAINT FK_program_program_type FOREIGN KEY (program_type_id) REFERENCES program_type(id)
);
