-- V003__create_notification_table.sql
-- AB#1891 Create notification table

CREATE TABLE notification (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id INT NOT NULL,
    notification_type NVARCHAR(50) NOT NULL,
    recipient_email NVARCHAR(200) NOT NULL,
    subject NVARCHAR(500) NOT NULL,
    body NVARCHAR(MAX) NOT NULL,
    sent_at DATETIME2,
    created_at DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME2,
    status NVARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT FK_notification_program FOREIGN KEY (program_id) REFERENCES program(id)
);
